version: '3.8'

services:
  app:
    restart: always
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db:ro
